on:
  pull_request:
    types: [closed]
    branches:
      - master

name: Move Jira task to resolved when merge

jobs:
  build:
    runs-on: ubuntu-latest
    name: Move Jira task to resolved when merge
    # if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Extract issue key
        id: issue
        run:  echo "::set-output name=key::$( [[ '${{ github.event.pull_request.title }}' =~ '{{([\s\S]+?)}}' ]] )"

      - name: Get key
        run: echo ${{ steps.issue.outputs.key }}
      # - name: Login
      #   uses: atlassian/gajira-login@master
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # - name: Find in commit messages
      #   id: find
      #   uses: cybervoid/gajira-get-issue@master
      #   with:
      #     input-text: ${{ github.head_ref }}
      # - name: Transition issue
      #   uses: atlassian/gajira-transition@master
      #   with:
      #     issue: ${{ steps.find.outputs.issue }}
      #     transition: Resolve
