on:
  push:
    branches:
      - master

name: Move Jira task to resolved when merge

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find in commit messages
        id: find
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: branch

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: format('[Cloud] {0}', steps.find.outputs.issue)
          transition: Close
