on:
  # pull_request:
  #   types: [closed]
  push
    branches:
      - master

name: Move Jira task to resolved when merge

jobs:
  build:
    runs-on: ubuntu-latest
    name: Move Jira task to resolved when merge
    steps:
      - name: Curl test
        run: curl --request POST \
          --url ${{ secrets.JIRA_BASE_URL }} \
          --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data '{

          "fields": {
          "project": {
          "key": "SEC"
          },
          "issuetype" : {
          "name" : "Incident"
          },
          "priority" : {
          "name" : "Highest"
          },
          "components" : [{
          "name" : "APE"
          }],
          "labels" : [
          "Bugfix"
          ],

          "summary": "Sample REST API.",
          "description": {
          "type": "doc",
          "version": 1,
          "content": [
          {
          "type": "paragraph",
          "content": [
          {
          "type": "text",
          "text": "example bug report"
          }
          ]
          }
          ]
          }
          },
          "properties": [
          {
          "key": "propertyKey",
          "value": "propertyValue"

          }
          ]
          }'

      # - name: Login
      #   uses: atlassian/gajira-login@master
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # - name: Find in commit messages
      #   id: find
      #   uses: cybervoid/gajira-get-issue@master
      #   with:
      #     input-text: ${{ github.head_ref }}
      # - name: Transition issue
      #   uses: atlassian/gajira-transition@master
      #   with:
      #     issue: ${{ steps.find.outputs.issue }}
      #     transition: Resolve
