on:
  push:
    branches:
      - master

name: Jira

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create new issue
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: NE
          issuetype: Task
          summary: |
            Build completed for ${{ github.repository }}
          description: |
            Compare branch

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "In progress"

      - name: Find in commit messages
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: commits
