on:
  # pull_request:
  #   types: [closed]
  push:
    branches:
      - master

name: Move Jira task to resolved when merge

jobs:
  build:
    runs-on: ubuntu-latest
    name: Move Jira task to resolved when merge
    steps:
      - name: Curl test
        uses: satak/webrequest-action@master
        id: create
        with:
          url: ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue
          method: POST
          payload: '{
            "fields": {
                "summary": "Sample REST API.",
                "project": {
                  "key": "NE"
                },
                "issuetype": {
                  "name": "Task"
                },
                "components": [
                  {
                    "name": "Cloud - Noodoe App"
                  }
                ]
              }
            }'
          headers: '{"Content-Type":"application/json", "Accept":"application/json"}'
          username: ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}

        # run: |
        #   curl --request POST \
        #   --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue \
        #   --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
        #   --header Accept:application/json \
        #   --header Content-Type:application/json \
        #   --data '{
        #     "fields": {
        #         "summary": "Sample REST API.",
        #         "project": {
        #           "key": "NE"
        #         },
        #         "issuetype": {
        #           "name": "Task"
        #         },
        #         "components": [
        #           {
        #             "name": "Cloud - Noodoe App"
        #           }
        #         ]
        #       }
        #     }'

      - name: Get key
        shell: pwsh
        run: |
          $output = '${{ steps.create.outputs.output }}' | ConvertFrom-Json
          echo $($output.key)
      # - name: Login
      #   uses: atlassian/gajira-login@master
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # - name: Find in commit messages
      #   id: find
      #   uses: cybervoid/gajira-get-issue@master
      #   with:
      #     input-text: ${{ github.head_ref }}
      # - name: Transition issue
      #   uses: atlassian/gajira-transition@master
      #   with:
      #     issue: ${{ steps.find.outputs.issue }}
      #     transition: Resolve
