on:
  pull_request:
    types: [opened]
    branches:
      - master

name: Bind this pull request to existed Jira issue

jobs:
  build:
    runs-on: ubuntu-latest
    name: Bind this pull request to existed Jira issue
    # DEV: unsupported regex or secrets injection
    if: "startsWith(github.event.pull_request.title, '[')"
    steps:
      - name: Extract issue key
        id: issue
        run: |
          echo "::set-output name=key::$(echo '${{ github.event.pull_request.title }}' |
            sed 's|^\[\([A-Z]\{1,\}-[0-9]\{1,\}\)\].*|\1|')"
      
      - name: Update issue and comment pull request link
        run: |
          curl -X POST \
            --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.issue.outputs.key }}/comment \
            --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            --header Accept:application/json \
            --header Content-Type:application/json \
            --data '{
              "body": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "blockCard",
                    "attrs": {
                      "url": "${{ github.event.pull_request.html_url }}"
                    }
                  }
                ]
              }
            }'

          transitions=$(curl -s -X GET \
            --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.issue.outputs.key }}/transitions \
            --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            --header Accept:application/json)

          transitionId=$(printf '%s' "$transitions" | jq -r '.transitions |
            map(select(.name | startswith("${{ secrets.JIRA_PR_TRANSITION_NAME }}")))[0].id')

          curl -X POST \
            --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.issue.outputs.key }}/transitions \
            --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            --header Accept:application/json \
            --header Content-Type:application/json \
            --data '{
              "transition": {
                "id": "'"${transitionId}"'"
              }
            }'

      - name: Edit pull request desc with jira issue link
        uses: tzkhan/pr-update-action@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-regex: .
          title-template: '[${{ steps.issue.outputs.key }}]' 
          replace-title: false
          title-prefix-space: true
          uppercase-title: true
          body-template: '[${{ steps.issue.outputs.key }}](${{ secrets.JIRA_BASE_URL }}/browse/${{ steps.issue.outputs.key }})'
          replace-body: false
          body-prefix-newline-count: 2
          uppercase-body: true
