on:
  pull_request:
    types: [opened]
    branches:
      - master

name: Create Jira task when pull request creation

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira task when pull request creation
    steps:
      - name: Create Issue
        id: create
        run: |
          echo "::set-output name=key::$( \
            curl -s --request POST \
            --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue \
            --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            --header Accept:application/json \
            --header Content-Type:application/json \
            --data '{
              "fields": {
                  "summary": "Sample REST API.",
                  "project": {
                    "key": "NE"
                  },
                  "issuetype": {
                    "name": "Task"
                  },
                  "components": [
                    {
                      "name": "Cloud - Noodoe App"
                    }
                  ]
                }
              }' \
            | jq '.key' | sed 's/\"//g')"

      - name: Find Issue Id
        id: Find
        run: |
          echo "::set-output name=id::$( \
            curl -s --request POST \
            --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue \
            --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            --header Accept:application/json \
            --header Content-Type:application/json \
            --data '{
              "fields": {
                  "summary": "Sample REST API.",
                  "project": {
                    "key": "NE"
                  },
                  "issuetype": {
                    "name": "Task"
                  },
                  "components": [
                    {
                      "name": "Cloud - Noodoe App"
                    }
                  ]
                }
              }' \
            | jq '.key' | sed 's/\"//g')"

      - name: Get key
        run: echo ${{ steps.create.outputs.key }}

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: Start Progress

      - name: Rename pull request title
        uses: tzkhan/pr-update-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-regex: *
          lowercase-branch: false
          title-template: ${{ steps.create.outputs.key }}
          replace-title: false
          title-prefix-space: true
          uppercase-title: true
          body-template: [${{ steps.create.outputs.key }}](https://noodoe.atlassian.net/browse/%branch%)
          replace-body: false
          body-prefix-newline-count: 2
          uppercase-body: true
