on:
  pull_request:
    types: [reopened]
    branches:
      - master

name: Create Jira task when pull request creation

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira task when pull request creation
    steps:
      - name: Create Issue
        id: create
        run: |
          res=$(curl -s -X POST \
            --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue \
            --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            --header Accept:application/json \
            --header Content-Type:application/json \
            --data '{
              "fields": {
                  "summary": "${{ github.event.pull_request.title }}",
                  "project": {
                    "key": "NE"
                  },
                  "issuetype": {
                    "name": "Task"
                  },
                  "components": [
                    {
                      "name": "Cloud - Noodoe App"
                    }
                  ]
                }
              }')
          echo "$res"
          echo "::set-output name=key::$(printf %s "$res" | jq -r '.key')"
          echo "::set-output name=id::$(printf %s "$res" | jq -r '.id')"

      - name: Transition Issue
        run: |
          curl -s -X POST \
            --url ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue/${{ steps.create.outputs.id }}/transitions \
            --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
            --header Accept:application/json \
            --header Content-Type:application/json \
            --data '{
                "transition": {
                  "id": "91"
                }
              }'

      - name: Rename pull request title
        uses: tzkhan/pr-update-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-regex: .
          lowercase-branch: false
          title-template: '[${{ steps.create.outputs.key }}]' 
          replace-title: false
          title-prefix-space: true
          uppercase-title: true
          body-template: '[${{ steps.create.outputs.key }}](https://noodoe.atlassian.net/browse/${{ steps.create.outputs.key }})'
          replace-body: false
          body-prefix-newline-count: 2
          uppercase-body: true
