on:
  pull_request:
    types: [opened]
    branches:
      - master

name: Create Jira task when pull request creation

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira task when pull request creation
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create new task
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: NE
          issuetype: Task
          summary: |
            [Cloud] ${{ github.ref }}

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: Start Progress

      - name: Rename pull request title
        uses: tzkhan/pr-update-action@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          branch-regex: 'NE-\d+'
          lowercase-branch: false
          title-template: "[%branch%]"
          replace-title: false
          title-prefix-space: true
          uppercase-title: true
          body-template: "[Link to %branch%](https://noodoe.atlassian.net/browse/%branch%)"
          replace-body: false
          body-prefix-newline-count: 2
          uppercase-body: true
