on:
  pull_request:
    types: [opened]
    branches:
      - master

name: Pull Request and Jira issue integration

jobs:
  jira:
    name: Pull Request and Jira issue integration
    runs-on: ubuntu-latest
    steps:
    - name: Pull Request and Jira issue integration
      uses: Timmatt-Lee/Github-Jira-Integration@master
      with:
        host: ${{ secrets.JIRA_BASE_URL }}
        email: ${{ secrets.JIRA_USER_EMAIL }}
        token: ${{ secrets.JIRA_API_TOKEN }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        project: ${{ secrets.JIRA_PROJECT_NAME }}
        transition: ${{ secrets.JIRA_PR_TRANSITION_NAME }}
        type: ${{ secrets.JIRA_ISSUE_TYPE }}
        component: ${{ secrets.JIRA_COMPONENT_NAME }}
        version: ${{ secrets.JIRA_VERSION_PREFIX }}
        board: ${{ secrets.JIRA_BOARD_ID }}
